variables:
image: bowmanhan/truffle-ci:latest

cache:
  paths:
  - node_modules/

stages:
- test

before_script:
  - rm -f package-lock.json
  - npm install


test_stage:
  stage: test
  only:
  - dev
  script:
   - truffle compile
   - nohup ganache-cli -q &
   - truffle migrate
   - truffle test
