variables:
image: bowmanhan/truffle-ci:latest

cache:
  paths:
  - node_modules/

stages:
- build
- test

before_script:
  - rm -f package-lock.json
  - npm install


build_stage:
  stage: build
  only:
  - dev
  script:
   - truffle compile

test_stage:
  stage: test
  only:
  - dev
  script:
   - ganache-cli
   - truffle migrate
   - truffle test
