variables:
image: bowmanhan/node:10.11.0-alpine

cache:
  paths:
  - node_modules/

stages:
- build

before_script:
  - npm install --progress=false


ci_compile:
  stage: build
  only:
  - dev
  script:
    truffle compile
