variables:
image: bowmanhan/truffle-ci:latest

cache:
  paths:
  - node_modules/

stages:
- build

before_script:
  - rm -f package-lock.json
  - npm install


ci_compile:
  stage: build
  only:
  - dev
  script:
   - truffle compile
